CREATE DATABASE AULA_EMPRESA;

USE AULA_EMPRESA;

CREATE TABLE DEPARTAMENTO(
	NUMERO INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DATA_INICIO DATETIME
);

CREATE TABLE PROJETO(
	NUMERO INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	LOCALIZACAO VARCHAR(50) NOT NULL,
	NUMERO_DEPTO INT NOT NULL,
	FOREIGN KEY (NUMERO_DEPTO) REFERENCES DEPARTAMENTO(NUMERO)
);

CREATE TABLE LOCALIZACOES(
	NUMERO_DEPTO INT NOT NULL,
	LOCALIZACAO VARCHAR(50) NOT NULL,
	FOREIGN KEY (NUMERO_DEPTO) REFERENCES DEPARTAMENTO(NUMERO),
	PRIMARY KEY (NUMERO_DEPTO, LOCALIZACAO)
);

CREATE TABLE EMPREGADO(
	NUMERO_SEGURO_SOCIAL INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(150) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	SEXO CHAR(1) CHECK(SEXO IN ('F', 'M', 'O')),
	RUA VARCHAR(50),
	NUMERO VARCHAR(10),
	NUMERO_DEPTO INT NOT NULL,
	NUMERO_SEGURO_SOCIAL_SUPERVISOR INT,
	FOREIGN KEY (NUMERO_DEPTO) REFERENCES DEPARTAMENTO (NUMERO),
	FOREIGN KEY (NUMERO_SEGURO_SOCIAL_SUPERVISOR) REFERENCES EMPREGADO(NUMERO_SEGURO_SOCIAL)
);

CREATE TABLE HORISTA(
	NUMERO_SEGURO_SOCIAL INT PRIMARY KEY NOT NULL,
	VALOR_HORA DECIMAL(8,2) NOT NULL,
	FOREIGN KEY (NUMERO_SEGURO_SOCIAL) REFERENCES EMPREGADO (NUMERO_SEGURO_SOCIAL)
);

CREATE TABLE ASSALARIADO(
	NUMERO_SEGURO_SOCIAL INT PRIMARY KEY NOT NULL,
	SALARIO DECIMAL(8,2) NOT NULL,
	FOREIGN KEY (NUMERO_SEGURO_SOCIAL) REFERENCES EMPREGADO (NUMERO_SEGURO_SOCIAL)
);

CREATE TABLE DEPENDENTE(
 CODIGO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 NUMERO_SEGURO_SOCIAL INT NOT NULL,
 NOME VARCHAR(150) NOT NULL,
 PARENTESCO VARCHAR(50),
 DATA_NASCIMENTO DATE NOT NULL,
 SEXO CHAR(1) CHECK (SEXO IN ('F', 'M', 'O')),
 FOREIGN KEY (NUMERO_SEGURO_SOCIAL) REFERENCES EMPREGADO (NUMERO_SEGURO_SOCIAL)
);

CREATE TABLE PROJETO_EMPREGADO(
	NUMERO_SEGURO_SOCIAL INT NOT NULL,
	NUMERO_PROJETO INT NOT NULL,
	FOREIGN KEY (NUMERO_SEGURO_SOCIAL) REFERENCES EMPREGADO (NUMERO_SEGURO_SOCIAL),
	FOREIGN KEY (NUMERO_PROJETO) REFERENCES PROJETO (NUMERO),
	PRIMARY KEY (NUMERO_SEGURO_SOCIAL, NUMERO_PROJETO)
);

ALTER TABLE EMPREGADO ADD BAIRRO VARCHAR(50) NOT NULL;

ALTER TABLE DEPARTAMENTO 
  ADD NUMERO_SEGURO_SOCIAL_SUPERVISOR INT NOT NULL;

ALTER TABLE DEPARTAMENTO
  ADD FOREIGN KEY (NUMERO_SEGURO_SOCIAL_SUPERVISOR) REFERENCES EMPREGADO(NUMERO_SEGURO_SOCIAL);
  
ALTER TABLE DEPARTAMENTO CHANGE COLUMN NUMERO_SEGURO_SOCIAL_SUPERVISOR NUMERO_SEGURO_SOCIAL_SUPERVISOR INT NULL;