val = input('Digite algo: ')
# f`strings
print(f'O tipo primitivo dessa valor e {type(val)}')
print(f'So tem espaços? {val.isspace()}')
print(f'E um numero? {val.isnumeric()}')
print(f'E alfabético? {val.isalpha()}')
print(f'E alfanumérico? {val.isalnum()}')
print(f'Esta em maiúsculo? {val.isupper()}')
print(f'Esta em minusculo? {val.islower()}')
print(f'Esta capitalizado? {val.istitle()}')

# Método .format()
print('O tipo primitivo desse valor e {}'.format(type(val)))
print('So tem espaços? {}'.format(val.isspace()))
print('E um numero? {}'.format(val.isnumeric()))
print('E alfabético? {}'.format(val.isalpha()))
print('E alfanumerico? {}'.format(val.isalnum()))
print('Esta em maisculas? {}'.format(val.isupper()))
print('Esta em minusculas? {}'.format(val.islower()))
print('Esta capitalizada? {}'.format(val.istitle()))

# Forma básica
print('O tipo primitivo desse valor e ', type(val))
print('So tem espaços? ', val.isspace())
print('E um numero? ', val.isnumeric())
print('E alfabético', val.isalpha())
print('E alfanumerico', val.isalnum())
print('Esta em maisculas? ', val.isupper())
print('Esta em minusculas? ', val.islower())
print('Esta capitalizada? ', val.istitle())