-- Exercício 2 - Alterando Assunto
UPDATE LIVRO SET ASSUNTO = 'Romance' WHERE ISBN = 9877150098;

-- Exercício 3 - Exluir um livro
DELETE FROM AUTOR WHERE LIVRO_ISBN = 9732157777;
DELETE FROM COMPRA WHERE LIVRO_ISBN = 9732157777;
DELETE FROM LIVRO WHERE ISBN = 9732157777;

-- Exercício 4
SELECT * FROM LIVRO ORDER BY ASSUNTO ASC;

-- Exercício 5
SELECT CLIENTE_CODIGO, DATA_COMPRA FROM COMPRA WHERE DATA_COMPRA BETWEEN '2021-03-01' AND '2021-03-30';

-- Exercício 6
SELECT ISBN, ASSUNTO, QUANTIDADE FROM LIVRO WHERE QUANTIDADE < 10 ORDER BY ASSUNTO ASC;

-- Exercício 7
SELECT LIVRO.ISBN, LIVRO.ASSUNTO, AUTOR.NOME, AUTOR.LIVRO_ISBN
FROM LIVRO
INNER JOIN AUTOR
ON AUTOR.LIVRO_ISBN = LIVRO_ISBN
ORDER BY LIVRO.ASSUNTO ASC;

-- Ecercício 8
SELECT CODIGO, NOME FROM CLIENTE WHERE NOME LIKE 'A%' ORDER BY NOME ASC;

-- Exercício 9
SELECT CLIENTE.NOME, CLIENTE.CODIGO, CLIENTE_FISICO.CPF
FROM CLIENTE
INNER JOIN CLIENTE_FISICO
ON CLIENTE.CODIGO = CLIENTE_FISICO.CLIENTE_CODIGO
WHERE CLIENTE.NOME LIKE 'A%'
ORDER BY CLIENTE.NOME ASC;

-- Exercício 10
SELECT COUNT(*) AS QUANTIDADE FROM COMPRA WHERE DATA_COMPRA BETWEEN '2021-03-01' AND '2021-03-30';

-- Exercício 11
SELECT SUM(QUANTIDADE) AS QUANTIDADE, EDITORA.CODIGO, EDITORA.NOME_GERENTE 
FROM LIVRO
INNER JOIN EDITORA
ON EDITORA.CODIGO = LIVRO.EDITORA_CODIGO
GROUP BY EDITORA.CODIGO;

-- Exercício 12
SELECT COUNT(CLIENTE_CODIGO) AS COMPROU, CLIENTE.CODIGO, CLIENTE.NOME
FROM COMPRA
INNER JOIN CLIENTE
ON CLIENTE.CODIGO = COMPRA.CLIENTE_CODIGO
GROUP BY CLIENTE.CODIGO;

-- Exercício 13
SELECT COUNT(LIVRO.ISBN) AS VENDIDO, LIVRO.ISBN, LIVRO.ASSUNTO
FROM COMPRA
INNER JOIN LIVRO
ON COMPRA.LIVRO_ISBN = LIVRO.ISBN
GROUP BY LIVRO.ISBN
ORDER BY VENDIDO DESC
LIMIT 1;