val = int(input('Digite um numero para ver sua tabua: '))
print('-'*12)
print(f'{val} x  1 = {val*1}')
print(f'{val} x  2 = {val*2}')
print(f'{val} x  3 = {val*3}')
print(f'{val} x  4 = {val*4}')
print(f'{val} x  5 = {val*5}')
print(f'{val} x  6 = {val*6}')
print(f'{val} x  7 = {val*7}')
print(f'{val} x  8 = {val*8}')
print(f'{val} x  9 = {val*9}')
print(f'{val} x 10 = {val*10}')
print('-'*12)